// Playwright CLI eval function; run after loading a fresh viewer page.
async () => {
  const assert = (value, message) => { if (!value) throw new Error(message); };
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const until = async (condition, message) => { const deadline = Date.now()+10000; while (!condition()) { if(Date.now()>deadline) throw Error(message); await wait(50); } };
  const set = (id, value) => { const element = document.getElementById(id); element.value = value; element.dispatchEvent(new Event('change')); };
  const done = v => v.paused && v.currentTime > v.duration - .04;
  const buttons = [...document.querySelectorAll('[data-replay]')];
  const shots = buttons.map(button => button.closest('article').querySelector('video'));
  assert(shots.length === 10, 'Ten one-shot cards required');
  assert(shots.every(v => v.paused && !v.loop && new URL(v.poster).pathname.endsWith('.png')), 'One-shots must start idle with posters');
  set('speed', '2');
  buttons.forEach(button => button.click());
  await until(() => shots.every(v => v.videoWidth === 384 && v.currentTime > 0), 'Replay must start all ten clips');
  await until(() => shots.every(v => done(v) && !v.seeking), 'All clips must reach their final frame');
  await wait(100);
  assert(shots.every(v => done(v) && !v.loop), 'One-shots must stop instead of looping');
  const alpha = shots.map(v => {
    const canvas = document.createElement('canvas'); canvas.width = canvas.height = v.videoWidth;
    const context = canvas.getContext('2d'); context.drawImage(v, 0, 0);
    const pixels = context.getImageData(0, 0, canvas.width, canvas.height).data;
    let max = 0; for (let i=3; i<pixels.length; i+=4) max = Math.max(max, pixels[i]);
    return {effect: v.dataset.effect, max};
  });
  assert(alpha.every(item => ['portal-open', 'vortex-opening'].includes(item.effect) ? item.max === 255 : item.max === 0), 'Wrong final-frame transparency');
  set('preview-rift-color', 'necrotic');
  await wait(100);
  assert(shots.every(done), 'Unrelated changes must not restart one-shots');
  const arrival = document.querySelector('video[data-effect="teleport-arrival"]');
  document.querySelector('[data-replay="teleport-arrival"]').click();
  await wait(150);
  assert(!arrival.paused && arrival.currentTime < 1.8, 'Replay must restart an ended one-shot');
  document.querySelector('#play').click();
  const time = arrival.currentTime;
  await wait(150);
  assert(arrival.paused && Math.abs(arrival.currentTime-time) < .02, 'Pause must hold active one-shots');
  document.querySelector('#play').click();
  await until(() => done(arrival) && !arrival.seeking, 'Resume must finish active one-shots');
  assert(shots.filter(v => v!==arrival).every(done), 'Resume must not restart completed clips');
  set('preview-teleport-arrival-color', 'psychic');
  await wait(100);
  assert(arrival.paused && new URL(arrival.poster).pathname.endsWith('/psychic.png'), 'Color changes must reset to an idle poster');
  const links = [...arrival.closest('article').querySelectorAll('a[download]')].map(a=>new URL(a.href).pathname.replace(/^\//, ''));
  assert(links.includes('assets/teleport-arrival/psychic.webm') && links.includes('assets/teleport-arrival/psychic.png'), 'Downloads must match color');
  set('rift-style', 'portal-open');
  const composed = document.querySelector('.composition > .rift');
  assert(!composed.loop && composed.paused, 'Composition one-shot must be idle');
  document.querySelector('#replay-composition').click();
  await until(() => done(composed) && !composed.seeking, 'Composition must finish one-shot');
  assert(document.querySelector('#status').hidden, 'Viewer reported an error');
  return {idlePosters: true, replay: true, finitePlayback: true, pauseResume: true, colorDownloads: true, composition: true, endpoints: alpha};
}
